### ISSUE TITLE
Migrate to new github actions

### ISSUE THREAD

**Issue by commjoen** [OWASP/owasp-mastg#1736]
In order to speed up reviewing & releasing, we need to :

- [ ] Fix the epub rendering (check document for links and images) and fix errors from `epubcheck OWASP_MSTG-SNAPSHOT-en.epub` 
- [ ] Fix the mobi rendering warnings/errors (missing images, links)
- [ ] Cleanup old materials
- [ ] Fix the PDF generation:
   - [ ] Reduce the TOC by one level, at the moment the TOC is 20 pages / TOC should have one or two levels less: `--toc-depth=3` not working right now.
   - [ ] `--number-sections` not taking effect
   - [ ] Look into Latex errors: #1772 (not a priority)
   - [ ] Fix links inside of the pdf:
      - [x] Broken links
      - [ ] Internal links broken (at least in Mac OS X Preview app, surely in other readers)
   - [x] Fix page layouts (new page and line breaks! Over and underflows) - SHOULD BE DONE LAST!
      - [x] Fix line breaks in problematic strings -> check "Notes" below.
   - [x] Fix cover so it spans over the whole page, at the moment there is a white border
   - [x] Fix images (make sure all are rendered: still need to fix some sizes & a few missing images);  page 657 and 845 pictures are missing @sushi2k   will look into it ([WARNING] Could not fetch resource 'Images/Chapters/0x5d/Android9_secure_key_import_to_keystore.png': PandocResourceNotFound "Images/Chapters/0x5d/Android9_secure_key_import_to_keystore.png")
   - [x] Level 6 headings (######) have no formatting and look like normal text. General Testing Guide, Android and iOS level 1 will be removed.  Generic / iOS and Android becomes a prefix of the sections. Need to consolidate also the wording of the titles (https://github.com/OWASP/owasp-mstg/pull/1775)
   - [x] Code is not properly highlighted. It just has another font and size, but no background or box around it: let's make sure always a supported language is chosen OR a new lib to support more langs.
- [x] Create new version of Docker Image as Syntax highlighting was added
- [x] Create MSTG generator container and push it to OWASP. registry at docker hub
- [x] Fix OWASP Logo, use new one from MASVS (being fixed in #1775)
- [x] Ensure consistency of chapter names (being fixed in #1775)
- [x] Remove empty files (being fixed in #1775)
- [x] Include Foreword (being fixed in #1775)
- [x] Add Trademark symbol for OWASP, as announced by Mike (NOTE: Projects that host outside of the owasp.org site/domain should as soon as is practical add a circle R (R) &reg; to the first prominent instance of the name OWASP and include this language in the footer of the site: "OWASP is a registered trademark of the OWASP Foundation, Inc."  The owasp.org homepage can be used as an example of this first step.)
- [x] Enable github actions for links and linting (see https://github.com/OWASP/owasp-mstg/pull/1735)

Run the new pipeline and create documents: `./tools/docker/run_docker_mstg_generation_on_local.sh`

### Notes 

Nots about to-be-fixed line-breaking issues (P: problem, S: solution):

```
P: this is not breaking line (causing overflow): **Protocol_KeyExchangeAlgorithm_WITH_BlockCipher_IntegrityCheckAlgorithm**
S: TO BE FIXED

P: Tables e.g. under "if data is rendered in a HTML context, six control characters that must be escaped:"
S: TO BE FIXED

P: The following is not breaking properly
"The module app.package.attacksurface",
"For example, \e search.quiet=true;", 
"are stored in clear text in /data/data/<package-name>/shared_-"
"stored in the clear text file /data/data/<package-name>/databases/privateNotSoSecure"
S: \newcommand*\justify... -> Verify if it's the best solution

P: The following is not breaking properly "A94A8FE5CCB19 ..."
S: TO BE FIXED

P: "Apple recommends using loadHTMLString:baseURL:/loadData"
"method loadFileURL:allowingReadAccessToURL"
"init(activityItems:applicationActivities:"
S:  TO BE FIXED

P: "contains a single file "WKWebView/scenario1.html" "
"kernel header file arch/arm/include/asm/unistd.h."
S:  TO BE FIXED
```

**Comment by commjoen** [comment]
We still have todos open...

**Comment by commjoen** [comment]
maybe we can include the open tasks of https://github.com/OWASP/owasp-mstg/issues/1156 here?

**Comment by commjoen** [comment]
<img width="1075" alt="Schermafbeelding 2020-05-29 om 11 14 27" src="https://user-images.githubusercontent.com/1457214/83243023-9c279a80-a19d-11ea-99af-f30ece71c135.png">
regarding pdf links...

**Comment by commjoen** [comment]
Propose : fix `Level 6 headings (######) have no formatting and look like normal text` by preprocessing: ######<content> -> _<content> _

**Comment by commjoen** [comment]
Maybe https://github.com/dalibo/pandocker/issues/168#issuecomment-660968845 can help?
